// react-app/src/App.js
import React from 'react';
import './App.css';

const App = () => {

  const onClickButton = () => {
    alert('Clicked!')
  }

  return (
    <div className="App">
      <h3>My React app using Stencil web components:</h3>
      <my-component first="Stencil" last="'Don't call me a framework' JS"></my-component>
      <jr-button variant="primary" onClick={onClickButton}>Button</jr-button>
    </div>
  );
}

export default App;

// angular-app/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'angular-app';

  onClickButton(): void {
    alert('Clicked!');
  }
}

<style>
  :host {
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";
    font-size: 14px;
    color: #333;
    box-sizing: border-box;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
  }

  .content {
    display: flex;
    margin: 82px auto 32px;
    padding: 0 16px;
    max-width: 960px;
    flex-direction: column;
    align-items: center;
  }
</style>

<div class="content" role="main">
  <h3>My Angular app using Stencil web components:</h3>
  <my-component first="Stencil" last="'Don't call me a framework' JS"></my-component>
  <jr-button variant="primary" (click)="onClickButton()">Button</jr-button>
</div>
